// validate-svg.js — GENERATED by scripts/build-n8n-snippets.mjs. Do not edit in n8n;
// edit scripts/lib/*.mjs in the repository, run `npm run n8n:snippets`, and paste.
// n8n Code node: mode "Run Once for All Items", language JavaScript.
// Purpose: Validate the generated SVG (json.svg). On any problem, drop the art (aiArt=false) so the section image is used.
/* eslint-disable */
// Strict safety validator for machine-generated editorial SVGs.
//
// AI-generated SVGs are served from the site's own origin, so they are
// treated as untrusted input. This is an allowlist validator: any element
// that is not a known-inert drawing primitive is rejected, and every
// attribute value is checked for executable or external content.
//
// It rejects rather than rewrites. A rejected file must be regenerated,
// never "cleaned" into something nobody reviewed.

const MAX_SVG_BYTES = 400 * 1024;

// Inert drawing, paint-server, text and filter primitives only.
// Deliberately excluded: script, foreignObject, a, image, feImage, iframe,
// embed, object, audio, video, animate*, set, handler, listener, style
// with external loads (style is allowed but its content is checked).
const ALLOWED_ELEMENTS = new Set([
  'svg', 'g', 'defs', 'title', 'desc', 'metadata', 'symbol', 'use',
  'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon',
  'text', 'tspan', 'textPath',
  'linearGradient', 'radialGradient', 'stop', 'pattern',
  'clipPath', 'mask', 'marker', 'style',
  'filter', 'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite',
  'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDistantLight',
  'feDropShadow', 'feFlood', 'feFuncA', 'feFuncB', 'feFuncG', 'feFuncR',
  'feGaussianBlur', 'feMerge', 'feMergeNode', 'feMorphology', 'feOffset',
  'fePointLight', 'feSpecularLighting', 'feSpotLight', 'feTile', 'feTurbulence'
]);

const HREF_ATTRS = new Set(['href', 'xlink:href']);

// Values that can execute code or pull in remote resources.
const DANGEROUS_VALUE_PATTERNS = [
  [/javascript\s*:/i, 'javascript: URL'],
  [/vbscript\s*:/i, 'vbscript: URL'],
  [/(^|[^a-z0-9-])data\s*:/i, 'data: URL'],
  [/[a-z][a-z0-9+.-]*:\/\//i, 'absolute/external URL'],
  [/(^|[^a-z0-9])\/\/[a-z0-9]/i, 'protocol-relative URL'],
  [/@import/i, '@import'],
  [/expression\s*\(/i, 'CSS expression()'],
  [/-moz-binding/i, '-moz-binding'],
  [/behavior\s*:/i, 'CSS behavior'],
  [/&#|&[a-z]+;.*:/i, 'encoded characters in a URL-like value']
];

function decodeBasicEntities(value) {
  return String(value)
    .replace(/&#x([0-9a-f]+);?/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);?/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
}

// Only same-document fragment references are allowed: url(#id).
function checkCssUrls(value, where, errors) {
  for (const m of String(value).matchAll(/url\s*\(\s*(['"]?)(.*?)\1\s*\)/gi)) {
    if (!/^#[A-Za-z_][\w.-]*$/.test(m[2].trim())) errors.push(`${where}: url() must reference a local #id, found "${m[2].slice(0, 80)}"`);
  }
}

function checkValue(value, where, errors) {
  const decoded = decodeBasicEntities(value);
  for (const candidate of [value, decoded]) {
    for (const [re, label] of DANGEROUS_VALUE_PATTERNS) {
      // The entity heuristic only applies to the raw value.
      if (label.startsWith('encoded') && candidate !== value) continue;
      if (re.test(candidate)) { errors.push(`${where}: blocked ${label}`); return; }
    }
  }
  checkCssUrls(decoded, where, errors);
}

function parseAttributes(raw, where, errors) {
  const attrs = [];
  let rest = raw;
  const re = /^\s+([^\s=/>"'<]+)\s*=\s*("([^"]*)"|'([^']*)')/;
  while (true) {
    const m = rest.match(re);
    if (!m) break;
    attrs.push({ name: m[1], value: m[3] ?? m[4] ?? '' });
    rest = rest.slice(m[0].length);
  }
  if (rest.replace(/\s+/g, '').replace(/\/$/, '') !== '') {
    errors.push(`${where}: malformed or unquoted attributes near "${rest.trim().slice(0, 60)}"`);
  }
  return attrs;
}

/**
 * Validate an SVG document string.
 * @returns {string[]} list of problems; empty means the SVG is acceptable.
 */
function validateSvg(source, label = 'svg') {
  const errors = [];
  const text = String(source ?? '');

  if (!text.trim()) return [`${label}: file is empty`];
  if (Buffer.byteLength(text, 'utf8') > MAX_SVG_BYTES) errors.push(`${label}: larger than ${MAX_SVG_BYTES} bytes`);
  if (/<!DOCTYPE|<!ENTITY/i.test(text)) errors.push(`${label}: DOCTYPE/ENTITY declarations are not allowed`);
  if (/<\?(?!xml\s)/i.test(text) || /<\?xml-stylesheet/i.test(text)) errors.push(`${label}: processing instructions are not allowed`);

  const body = text.replace(/^﻿?\s*(<\?xml\s[^?]*\?>\s*)?/i, '').replace(/^(\s*<!--[\s\S]*?-->\s*)*/, '');
  if (!/^<svg[\s>]/.test(body)) errors.push(`${label}: document must start with an <svg> root element`);

  const stack = [];
  let rootCount = 0;
  let i = 0;
  while (i < text.length) {
    const lt = text.indexOf('<', i);
    if (lt < 0) break;
    const where = `${label} (offset ${lt})`;

    if (text.startsWith('<!--', lt)) {
      const end = text.indexOf('-->', lt + 4);
      if (end < 0) { errors.push(`${where}: unterminated comment`); break; }
      i = end + 3; continue;
    }
    if (text.startsWith('<![CDATA[', lt)) {
      const end = text.indexOf(']]>', lt + 9);
      if (end < 0) { errors.push(`${where}: unterminated CDATA`); break; }
      const parent = stack[stack.length - 1];
      if (parent !== 'style') errors.push(`${where}: CDATA is only allowed inside <style>`);
      checkValue(text.slice(lt + 9, end), `${where} <style> CDATA`, errors);
      i = end + 3; continue;
    }
    if (text.startsWith('<?', lt)) {
      const end = text.indexOf('?>', lt);
      if (end < 0) { errors.push(`${where}: unterminated declaration`); break; }
      i = end + 2; continue; // xml declaration; others rejected above
    }
    if (text.startsWith('<!', lt)) { errors.push(`${where}: markup declarations are not allowed`); i = lt + 2; continue; }

    const gt = text.indexOf('>', lt);
    if (gt < 0) { errors.push(`${where}: unterminated tag`); break; }
    const tag = text.slice(lt + 1, gt);

    if (tag.startsWith('/')) {
      const name = tag.slice(1).trim();
      const open = stack.pop();
      if (open !== name) errors.push(`${where}: mismatched closing tag </${name}> (expected </${open ?? 'none'}>)`);
      i = gt + 1; continue;
    }

    const nameMatch = tag.match(/^([A-Za-z][\w:.-]*)/);
    if (!nameMatch) { errors.push(`${where}: invalid tag`); i = gt + 1; continue; }
    const name = nameMatch[1];
    const selfClosing = /\/\s*$/.test(tag);
    const local = name.includes(':') ? name.split(':').pop() : name;

    if (!ALLOWED_ELEMENTS.has(name)) errors.push(`${where}: element <${name}> is not allowed`);
    if (stack.length === 0) {
      rootCount++;
      if (local !== 'svg') errors.push(`${where}: root element must be <svg>`);
    }

    const attrs = parseAttributes(tag.slice(name.length).replace(/\/\s*$/, ''), `${where} <${name}>`, errors);
    for (const { name: attr, value } of attrs) {
      const attrWhere = `${where} <${name} ${attr}>`;
      const lower = attr.toLowerCase();
      const attrLocal = lower.includes(':') ? lower.split(':').pop() : lower;
      if (attrLocal.startsWith('on')) { errors.push(`${attrWhere}: event handler attributes are not allowed`); continue; }
      if (lower === 'xmlns' || lower.startsWith('xmlns:')) {
        if (!['http://www.w3.org/2000/svg', 'http://www.w3.org/1999/xlink'].includes(value)) errors.push(`${attrWhere}: unexpected namespace "${value}"`);
        continue;
      }
      if (lower.startsWith('xml:') && lower !== 'xml:space' && lower !== 'xml:lang') { errors.push(`${attrWhere}: attribute not allowed`); continue; }
      if (HREF_ATTRS.has(lower) || attrLocal === 'href') {
        if (!/^#[A-Za-z_][\w.-]*$/.test(value.trim())) errors.push(`${attrWhere}: href must reference a local #id`);
        continue;
      }
      checkValue(value, attrWhere, errors);
    }

    if (!selfClosing) {
      stack.push(name);
      if (name === 'style') {
        const close = text.indexOf('</style>', gt);
        if (close < 0) { errors.push(`${where}: unterminated <style>`); break; }
        const css = text.slice(gt + 1, close);
        if (/<(?!!\[CDATA\[)/.test(css.replace(/<!\[CDATA\[[\s\S]*?\]\]>/g, ''))) errors.push(`${where}: markup inside <style> is not allowed`);
        checkValue(css.replace(/<!\[CDATA\[|\]\]>/g, ''), `${where} <style>`, errors);
        stack.pop();
        i = close + '</style>'.length;
        continue;
      }
    }
    i = gt + 1;
  }

  if (stack.length) errors.push(`${label}: unclosed element(s): ${stack.join(', ')}`);
  if (rootCount !== 1) errors.push(`${label}: expected exactly one root <svg> element, found ${rootCount}`);
  return errors;
}

// ---- node body -------------------------------------------------------------
return $input.all().map(item => {
  const svg = String(item.json.svg || '');
  const problems = svg ? validateSvg(svg, 'editorial-svg') : ['no svg'];
  return { json: { ...item.json, aiArt: problems.length === 0, svg: problems.length ? '' : svg, svgProblems: problems } };
});
